[cosmic-ray]
module-path = "to_do_list.py"
python-version = "3"
timeout = 120  # Збільшуємо таймаут
excluded-modules = ["test_case.py"]  # Виключаємо тестовий файл
test-command = "python -m unittest test_case.py"

[execution-engine]
name = "local"

[cosmic-ray.distributor]
name = "local"

[cosmic-ray.filters.operators-filter]
operators = [
    "arithmetic_operator_replacement",
    "break_continue",
    "comparison_operator_replacement",
    "logical_operator_replacement",
    "number_replacer",
    "return_values",
    "exception_replacer",
    "conditional_expression",
    "boolean_replacer",
    "string_replacer",
    "attribute_replacer",
]
operator-exclude = [
    "unicode-decode-error",
    "mutate_module_imports",
    "remove_decorator",
    "zero_iteration_loop",
]
no-mutation = [
    "def __init__",
    "def task_exists",
]